### ISSUE TITLE
Cambio en tabla de factores para cálculo de la prima

### ISSUE THREAD

**Issue by cmonsalvec** [ivinces/Calculo-Prima#1]
Estimados,

De acuerdo a las estadísticas del 2019 hemos comprobado que la siniestralidad de conductores de 65 años de edad o más ha aumentado. Por tal razón el directorio de nuestra empresa ha decidido modificar para este rango de edad el número de puntos que puede perder en su licencia de conducir. El directorio ha aprobado que ese número de puntos pase de 5 a 4.

Por favor realizar los cambios en el sistema para que esta nueva disposición del directorio pueda entrar en funcionamiento.

**Comment by pedrojms** [comment]
De acuerdo con este incidente, se modificará la cantidad de puntos máximos permitidos que pueden perder en su licencia las personas de 65 años o más, pasando de permitir perder 5 puntos en su licencia a perder solo 4 para otorgarle la reducción por conductor seguro.
Es decir, para obtener el descuento por conductor seguro, estas personas en este rango de edad deberán tener mínimo 26 puntos en su licencia y ya no 25.
Esto implica un pequeño cambio en la función que calcula el valor de la reducción al valor total de la prima.

**Comment by pedrojms** [comment]
Se realizó un análisis del impacto del incidente. 
No se trata de un error sino más bien de una modificación.
Ciertamente para nuestro código el incidente no responde a una gran criticidad ya que se trata de un pequeño cambio en el valor definido en la cantidad de puntos permitidos para un cierto rango de edad en una función aparte que se tiene a la del cálculo del valor total de la prima.
No tomaría mucho tiempo ni gran costo en realizar este cambio.
@cmonsalvec ¿está usted de acuerdo?
Si es así, se le asigna la siguiente etapa a mi compañera @ivinces

**Comment by cmonsalvec** [comment]
Si, por favor, continuar con la implementación del cambio solicitado. Gracias

**Comment by ivinces** [comment]
Se realizó el cambio en la programación del código, se le asigna a @fannyvalverdem, realizar las pruebas de sistema y de integración.

**Comment by fannyvalverdem** [comment]
Se realizaron las pruebas de sistema y su documentación, se le asigna a @juanjofs96, realizar pruebas de aceptación
![pruebas_gestion_acc](https://user-images.githubusercontent.com/20008895/72951389-31340600-3d5c-11ea-9eb4-75d8f6c3704e.png)

**Comment by juanjofs96** [comment]
Se realizaron las pruebas de aceptacion exitosamente, @cmonsalvec favor confirmar para proceder a cerrar el issue. 
![captura aceptacion](https://user-images.githubusercontent.com/39098555/73022986-989f9380-3df8-11ea-8a0d-c86cd3ddbfd6.png)

**Comment by cmonsalvec** [comment]
Excelente, muchas gracias. Favor proceder con el cambio.
